FROM debian:12-slim

WORKDIR /isolated
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

COPY compiler /isolated/compiler

ENV PLUME_PATH /isolated/compiler/standard/

RUN ["chmod", "+x", "/isolated/compiler/bin/plume"]

ENTRYPOINT [ "/isolated/compiler/bin/plume" ]